### ISSUE TITLE
Radiotray-NG does not handle Icecast streams properly

### ISSUE THREAD

**Issue by wasikan-git** [ebruck/radiotray-ng#199] opened 2023-05-02 20:44 UTC
Hi!
I think there's a bug in Radiotray-NG.
Try this stream https://stream.radiobaobab.pl/radiobaobab.ogg.
It works perfectly via a web browser but if I open it in Radiotray-NG it will stop as soon as the current song ends, i.e. Radiotray will not continue to play the stream.

Regards
Andrzej

**Comment by ebruck** [comment] 2023-05-03 04:06
This could be the same issue as https://github.com/ebruck/radiotray-ng/issues/158.

**Comment by ebruck** [comment] 2023-05-03 04:10
There is an alternate stream you can use: http://stream.radiobaobab.pl:8000/radiobaobab.mp3

**Comment by wasikan-git** [comment] 2023-05-03 16:55
Hi,
yes, the mp3 stream works as expected.
Anyway, there's something wrong about the way RG-NG handles the ogg stream since the browser (Firefox, Mint 21.1) and VLC play it without any problems.

Regards
Andrzej

**Comment by ebruck** [comment] 2023-06-04 22:16
Duplicate of #158

**Closed by ebruck** 2023-06-04 22:16 UTC
