### ISSUE TITLE
Ogg streams halt after a few minutes playing

### ISSUE THREAD

**Issue by PorkPieHat** [ebruck/radiotray-ng#168] opened 2021-04-27 15:50 UTC
Ogg streams halt after a couple of minutes in my Majaro "Nibia" install. Try this:

https://stream.radioparadise.com/rp_192m.ogg

The problem affected the original radiotray. See this bug report (post #27):

https://bugs.launchpad.net/ubuntu/+source/radiotray/+bug/1557115

A variant of the bug also affected radiotray-lite. See here:

https://github.com/thekvs/radiotray-lite/issues/11

This bug was fixed, however

This is a small issue in a great app - but an irritating one

**Comment by PorkPieHat** [comment] 2021-04-29 09:49
I would say that the issue has to do with the apps handling of metadata in ogg streams. The radio paradise stream quoted above halts on track changes.

This stream - no metadata - plays OK:

[](https://stream.radioparadise.com/rp_192.ogg)

**Comment by PorkPieHat** [comment] 2021-04-29 09:50
This stream:

[](https://stream.radioparadise.com/rp_192.ogg)

**Comment by PorkPieHat** [comment] 2021-04-29 09:51
This stream:

https://stream.radioparadise.com/rp_192.ogg

**Comment by ebruck** [comment] 2021-04-29 19:16
This is a duplicate of https://github.com/ebruck/radiotray-ng/issues/158.
There's nothing I can do to address this.

**Closed by ebruck** 2021-04-29 19:16 UTC
