### ISSUE TITLE
The area where song title and artist are displayed is too small / TUXEDO OS 2 (Ubuntu 22.04.2 jammy)

### ISSUE THREAD

**Issue by HeidrHH** [ebruck/radiotray-ng#202] opened 2023-06-17 22:46 UTC
Radiotray v0.2.8-2-g7fe8c4a

Operating System: TUXEDO OS 2 (Ubuntu 22.04.2 jammy)
https://www.tuxedocomputers.com/en/TUXEDO-OS_1.tuxedo# 
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.106.0
Qt Version: 5.15.9
Kernel Version: 6.2.0-10007-tuxedo (64-bit)

The area where song title and artist are displayed is too small:

![Area for title and artist too small_20230618_003252_smaller](https://github.com/ebruck/radiotray-ng/assets/136175324/746e9215-65a5-46f2-9ed1-cf51dac35cd5)

**Comment by ebruck** [comment] 2023-06-19 00:06
duplicate of #159

**Closed by ebruck** 2023-06-19 00:06 UTC
